title = "200 social"
baseurl = "https://julioh.github.io"
publishdir = "public"
contentdir = "src/hugo/content"
layoutdir = "src/hugo/layouts"
staticdir = "src/hugo/static"
themesdir = "src/hugo/themes"

[params]
  # Meta parameters.
  encoding = "utf-8"
  description = ""
  DefaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 0
languageName = "English"

[[Languages.en.menu.main]]
url    = "/#about"
name   = "What is $200 Social Media"
weight = 1
[[Languages.en.menu.main]]
url    = "/#benefits"
name   = " Who is the 200 Social Team?"
weight = 2
[[Languages.en.menu.main]]
url    = "/#contact"
name   = " Contact $200 Social"
weight = 3


[blackfriday]
  hrefTargetBlank = true


